rootProject.name = "vbookstore"
include("vbookstore.domain")
include("vbookstore.data")
include("vbookstore.web")
include("vbookstore.restclient")
include("app")
include("vbookstore.api")
include("core")
include("commons")
include("security")
